name: Check PR for changes in autopts/wid/

on:
  pull_request_target:
    types: [ready_for_review, opened]
    branches:
      - master

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes in autopts/wid directory
        id: check_changes
        run: |
          python .github/check_for_changes.py
          if [ changed_files_formatted.txt ]; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
          else
            echo "changes_detected=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Print Current Working Directory
        run: |
          pwd

      - name: Set output
        id: set_output
        if: ${{ steps.check_changes.outputs.changes_detected }} == 'true'
        run: |
          echo "changed_files=$(cat changed_files_formatted.txt)" >> $GITHUB_OUTPUT

      - name: Print changed
        if: ${{ steps.check_changes.outputs.changes_detected }} == 'true'
        run: |
          echo "Changed files: ${{ steps.set_output.outputs.changed_files }}"

      - name: Post comment on PR
        if: ${{ steps.check_changes.outputs.changes_detected }} == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            \#AutoPTS run mynewt ${{ steps.set_output.outputs.changed_files }} --test-case-limit 10
